"""store refresh tokens

Revision ID: 1c4ab9b44bfc
Revises: 928d108fe382
Create Date: 2026-08-20 22:50:36.416766

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "1c4ab9b44bfc"
down_revision: Union[str, Sequence[str], None] = "928d108fe382"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admin",
        sa.Column("refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "refresh_token")
    op.drop_column("admin", "refresh_token")
    # ### end Alembic commands ###
