"""change user table

Revision ID: 928d108fe382
Revises: 3c658d23abc0
Create Date: 2026-08-10 12:04:05.243248

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "928d108fe382"
down_revision: Union[str, Sequence[str], None] = "3c658d23abc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admin",
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "admin",
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.drop_column("admin", "password")
    op.drop_column("admin", "name")
    op.add_column(
        "theater", sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column(
        "user",
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "user",
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.drop_column("user", "password")
    op.drop_column("user", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("name", sa.VARCHAR(), nullable=False))
    op.add_column("user", sa.Column("password", sa.VARCHAR(), nullable=False))
    op.drop_column("user", "hashed_password")
    op.drop_column("user", "username")
    op.drop_column("theater", "name")
    op.add_column("admin", sa.Column("name", sa.VARCHAR(), nullable=False))
    op.add_column("admin", sa.Column("password", sa.VARCHAR(), nullable=False))
    op.drop_column("admin", "hashed_password")
    op.drop_column("admin", "username")
    # ### end Alembic commands ###
